package com.Sumanta.caremate.enums;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_COMPLETED,
    BOOKING_CANCELLED,
    REVIEW_RECEIVED,
    PAYMENT_RECEIVED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_EXPIRED,
    PROFILE_UPDATED,
    GENERAL
}